name: Firebase Functions Deploy
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'main/functions/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'main/functions/**'
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  function_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 16.x
      - uses: actions/cache@v2
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/main/functions/package-lock.json') }}
            restore-keys: ${{ runner.os }}-node-
      - name: Build Cloud Functions
        run: cd main && cd functions && npm install
      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && cd main && npx firebase-tools deploy --only functions --json