name: Course 1 Hosting Deploy
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'main/public/**'
      - 'main/.firebaserc'
      - 'main/firebase.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'main/public/**'
      - 'main/.firebaserc'
      - 'main/firebase.json'
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  function_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Deploy Functions
        uses: BIGG-Kaymo/deploy-firebase-functions@v1.0.1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}